#!/bin/bash

echo

# Check to see if in the right base directory
CURRENT_BASE_DIR=${PWD##*/}
if [ $CURRENT_BASE_DIR = "TC-monitor" ]
then
    # Virtual enviromnment for flask application
    echo "[TC-Monitor] - Checking if virtual enviroment is setup ..."
    if [ -d ./env ]   # Check to see if virtual enviroment exists in current working directory
    then
        echo "[TC-Monitor] - Virtual environment already exists (./env)"
        echo "[TC-Monitor] - Activating virtual enviroment ..."
        source env/bin/activate                      # Activate virtual enviroment
    else
        echo "[TC-Monitor] - Creating a virtual environment for web application (./env) ..."
        python3 -m venv env               # Creating the virtual environment
        echo "[TC-Monitor] - Activating virtual enviroment ..."
        source env/bin/activate                      # Activate virtual enviroment
        echo "[TC-Monitor] - Installing all required python packages ..."
        pip3 install -U -r requirements.txt     # Install all required packages for virtual environment
    fi

    # Running the flask application
    echo "[TC-Monitor] - Starting web application ..."
    echo
    python3 main.py
    echo
    echo "[TC-Monitor] - Web application has stopped"

    # TODO: Add watchdog for app crashes
else
    # Current directory is not correct
    echo
    echo "[TC-Monitor] - CRITICAL! - Application was not able to start up!"
    echo "[TC-Monitor] - CRITICAL! - Shell script not executed within the correct directory"
    echo
fi
